newcommers guide
Mokusho-Zen-Bulgaria/mokusho-zen-bulgaria.github.io pull request #7
Opened 2024-05-05 20:09 UTC by abuseofnotation

2024-10-12 08:04 UTC, kanmeiban requested changes
Боби, благодаря ти за старанието и извинявай, че чак сега отделих време да го прегледам. Текстът се нуждае от много поправки, за да не е в разрез с духа на традицията на нашата приемствена линия.

2024-10-12 08:04 UTC, kanmeiban commented on index.md
> +Освен на събития, ние се събираме всяка седмица, за да практикуваме Зазен в София и Варна.
Не Зазен, а дзадзен. Пише се с малка буква. В японския няма звук „з“, а в английския „дз“

2024-10-12 08:04 UTC, kanmeiban commented on index.md
> -## Мокушо дзен група Варна
Защо си го махнал?

2024-10-12 08:04 UTC, kanmeiban commented on index.md
> -Всяка пролет и есен организираме неколкодневен сешшин – това е период на интензивна дзен практика, в който неспирният поток на мислите ни бива заменен от съсредоточаване във всичко, което правим. За
Защо си го махнал?

2024-10-12 08:04 UTC, kanmeiban commented on newcommers.md
> +Отнасяме се с дълбоко уважение към любопитството и куража, на хората, които са готови да опитат нещо ново, и искаме да Ви кажем, че независимо дали това ще е първият път в който ще медитирате, или им
Дзадзен не е медитация

2024-10-12 08:04 UTC, kanmeiban commented on newcommers.md
> +При нас ще чуете звън от камбани, рецитали на сутри и може да се натъкнете на практики, които са ви непознати. Не чувствайте неудобство от това че не знаете всички тези "форми"*. Ако ви харесва, напр
Учителят Мьокен казва „Стремежът да разбираш е най-голямото препятствие в практиката“.

2024-10-12 08:04 UTC, kanmeiban commented on newcommers.md
> +При нас ще чуете звън от камбани, рецитали на сутри и може да се натъкнете на практики, които са ви непознати. Не чувствайте неудобство от това че не знаете всички тези "форми"*. Ако ви харесва, напр
В нашата практика няма „харесва ми – не ми харесва“, „искам – не искам“. Когато  пристъпиш прага на дожото, оставяш отвън личните си пристрастия, желания и прищевки.

2024-10-12 08:04 UTC, kanmeiban commented on newcommers.md
> +"Форми" са структурираните начини по които извършваме дейности в Зен традицията. Те са много и никой не владее всички тях перфектно. Също никой от нас не ги е знаел когато е започвал и всички ние все
Учителят ни е казвал многократно: в дожото няма грешки! Също така че да се колебаеш е по-лошо от това да сбъркаш. Да действаш без да разсъждаваш рационално, а като следваш космическия порядък – това е най-висшата форма на действие!

2024-10-20 09:54 UTC, abuseofnotation commented on index.md
> -Всяка пролет и есен организираме неколкодневен сешшин – това е период на интензивна дзен практика, в който неспирният поток на мислите ни бива заменен от съсредоточаване във всичко, което правим. За
Хм, не съм не знам защо така излиза...

2024-10-20 10:02 UTC, abuseofnotation commented on newcommers.md
> +При нас ще чуете звън от камбани, рецитали на сутри и може да се натъкнете на практики, които са ви непознати. Не чувствайте неудобство от това че не знаете всички тези "форми"*. Ако ви харесва, напр
ОК

2024-10-20 10:02 UTC, abuseofnotation commented on newcommers.md
> +"Форми" са структурираните начини по които извършваме дейности в Зен традицията. Те са много и никой не владее всички тях перфектно. Също никой от нас не ги е знаел когато е започвал и всички ние все
Оправям

2024-10-29 10:50 UTC, abuseofnotation commented on index.md
> -## Мокушо дзен група Варна
Така излиза, нз защо

2025-02-13 15:25 UTC, kanmeiban commented
@abuseofnotation черешобернах ръчно няколко промени по текста и ги приложих във master. Не включих обяснението за новодошли, защото е многословно. Когато нови хора дойдат в дожото, всички тези неща им ги казваме така и така. Благодаря за старанието /_||_\

2025-02-13 15:25 UTC, closed without merging