designs
Mokusho-Zen-Bulgaria/mokusho-zen-bulgaria.github.io pull request #8
Opened 2024-11-13 06:52 UTC by abuseofnotation

2024-11-13 12:37 UTC, kanmeiban requested changes

2024-11-13 12:37 UTC, kanmeiban commented on designs/poster.svg
Цитатът на плаката е с дребен шрифт и има много голямо разстояние между редовете,

2024-11-13 12:37 UTC, kanmeiban commented on designs/zen_chants_translation.svg
Бележките под линия изглеждат като част от текста. Те са в три колони, а текста в две и е дисхармонично.

2024-11-13 13:34 UTC, abuseofnotation commented on designs/zen_chants_translation.svg
Подредбата не е случайна - лявата колона са думи, които се срещат в лявата колона на текста, дясната, в дясната колона, а средната са най-фундаменталните думи.

2024-11-13 13:37 UTC, abuseofnotation commented on designs/poster.svg
Това е за да може да има повече място за надписа, нали е табела.
Освен това, така подравняването е красиво, и е едно изречение на ред.

2024-11-14 03:52 UTC, kanmeiban commented on designs/zen_chants_translation.svg
Махни речника изцяло. По-добре е  пълен превод на сутрата, отколкото откъслечни думи.

2024-11-14 03:53 UTC, kanmeiban commented on designs/poster.svg
Табелата е необходимо да може да бъде и четена, не е само за красота. Търсим баланс между форма и функция.

2025-02-13 15:42 UTC, kanmeiban commented
Слях ги през терминала.

2025-02-13 15:42 UTC, closed without merging